<?php

namespace Application\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlassGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassGroupRepository extends EntityRepository
{
}
