<?php

namespace Application\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportStudentRepository extends EntityRepository
{
    public function add($students)
    {
        foreach ($students as $student) {

            $rStudent = new ReportStudent();
            $reportTransfer = new ReportTransfer();

            $transfer = $student->getTransfer();

            $rStudent->setAddress($student->getAddress());
            $rStudent->setBirthday($student->getBirthDay());
            $rStudent->setClassGroup($student->getClassGroup()->__toString());
            $rStudent->setFirstname($student->getFirstname());
            $rStudent->setLastname($student->getLastname());
            $rStudent->setNationality($student->getNationality()->getName());
            $rStudent->setPersonalNumber($student->getPersonalNumber());
            $rStudent->setSex($student->getSex());
            $rStudent->setTelephone($student->getTelephone());

            if ($transfer) {
                $reportTransfer->setMoved($transfer->getMoved());
                $reportTransfer->setPlace($transfer->getPlace());
                $reportTransfer->setDate($transfer->getDate());
                $rStudent->setTransfer($reportTransfer);
            }
            $em = $this->getEntityManager();
            $em->persist($rStudent);
            $em->flush();

        }

        return true;
    }

    public function byYear(ReportClass $class)
    {

        return $this->getEntityManager()
            ->createQuery("select year(st.birthday) as y,sum( case when (st.sex='М') then 1 else 0 end ) as male, sum(case when (st.sex='Ж') then 1 else 0 end) as female, count(st.id) as total from ApplicationSchoolBundle:ReportStudent st join st.reportClass cg where cg = :g group by y order by y asc")->setParameter('g', $class)
            ->getResult();
    }

    public function byNationality(ReportClass $class)
    {
        return $this->getEntityManager()
            ->createQuery("select st.nationality,sum( case when (st.sex='М') then 1 else 0 end ) as male, sum(case when (st.sex='Ж') then 1 else 0 end) as female, count(st.id) as total from ApplicationSchoolBundle:ReportStudent st join st.reportClass cg where cg = :g  group by st.nationality order by st.nationality asc")->setParameter('g', $class)
            ->getResult();
    }
}
