school_main_index:
    pattern:  /
    defaults: { _controller: ApplicationSchoolBundle:Main:index }
school_classgroup_list:
    pattern:  /classgroups
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:list }

school_classgroup_get:
    pattern:  /classgroups/{id}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:get }

school_classgroup_alphabet:
    pattern: /classgroups/grade/{grade}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:alphabet }
    options:
        expose:  true

school_academicyear_list:
    pattern:  /academicyears
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:list }

school_academicyear_get:
    pattern: /academicyears/
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:get }

school_report_index:
    pattern:  /report/index
    defaults: { _controller: ApplicationSchoolBundle:Report:index }

school_report_create:
    pattern: /report/create
    defaults: { _controller: ApplicationSchoolBundle:Report:create }

classgroup_report_classgroup:
    pattern:  /report/classgroup/{id}/report/{type}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:classGroup, type: json }

classgroup_report_list:
    pattern:  /report/classgroup/{id}/list/{type}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:reportList, type: json }

student_extract:
    path: /report/extract
    defaults: { _controller:  ApplicationSchoolBundle:Student:extract }

student_summer:
    path: /report/whole
    defaults: { _controller:  ApplicationSchoolBundle:Student:summer }