school_main_index:
    pattern:  /
    defaults: { _controller: ApplicationSchoolBundle:Main:index }
school_classgroup_list:
    pattern:  /classgroups
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:list }

school_classgroup_get:
    pattern:  /classgroups/{id}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:get }

school_academicyear_list:
    pattern:  /academicyears
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:list }

school_academicyear_get:
    pattern: /academicyears/
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:get }

school_report_index:
    pattern:  /report/index
    defaults: { _controller: ApplicationSchoolBundle:Report:index }
