school_main_index:
    pattern:  /
    defaults: { _controller: ApplicationSchoolBundle:Main:index }

shool_classgroup_upgrade:
    path: /upgrade
    defaults: { _controller:  ApplicationSchoolBundle:ClassGroup:upgrade }

school_classgroup_list:
    pattern:  /classgroups
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:list }

school_classgroup_get:
    pattern:  /classgroups/{id}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:get }

school_classgroup_alphabet:
    pattern: /classgroups/grade/{grade}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:alphabet }
    options:
        expose:  true

school_academicyear_list:
    pattern:  /academicyears
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:list }

school_academicyear_get:
    pattern: /academicyears/{id}/quarters
    defaults: { _controller: ApplicationSchoolBundle:AcademiYear:get }

school_report_index:
    pattern:  /reports/
    defaults: { _controller: ApplicationSchoolBundle:Report:index }


school_report_create:
    pattern: /report/create
    defaults: { _controller: ApplicationSchoolBundle:Report:create }

school_report_delete:
    path: /report/{id}/delete
    defaults: { _controller:  ApplicationSchoolBundle:Report:delete }

classgroup_report_classgroup:
    pattern:  /report/classgroup/{id}/report/{type}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:classGroup, type: json }

classgroup_report_list:
    pattern:  /report/classgroup/{id}/list/{type}
    defaults: { _controller: ApplicationSchoolBundle:ClassGroup:reportList, type: json }

student_extract:
    path: /report/extract
    defaults: { _controller:  ApplicationSchoolBundle:Student:extract }

student_summer:
    path: /report/whole
    defaults: { _controller:  ApplicationSchoolBundle:Student:summer }

report_history_add:
    path: /report/history/add
    defaults: { _controller:  ApplicationSchoolBundle:Report:addToHistory }

report_report:
    path: /reports/{id}
    defaults: { _controller:  ApplicationSchoolBundle:Report:report  }

report_report_class:
    path: /reportclass/{id}/more-info
    defaults: { _controller:  ApplicationSchoolBundle:ReportClass:class }

report_report_report:
    path: /reportclass/{id}/report
    defaults: { _controller:  ApplicationSchoolBundle:ReportClass:report }